### ISSUE TITLE
[question]roadmap?

### ISSUE THREAD

**Issue by lichunqiang** [hscstudio/angular1-yii2#3]
Hi buddies,

What's the roadmap about this project.

It's too simple now and easy to understand.

What i want to known about:
- how to control the url access, eg: some path can be accessed after  login
- follow the first, with rbac

and etc...

Thanks!

**Comment by hscstudio** [comment]
Please check in customization section..

**Comment by lichunqiang** [comment]
a ha..  I saw that. Waiting for that anyway
